sudo: required
services:
  - docker
before_install:
  - docker build -t harry1989/fibonacci-client -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true harry1989/fibonacci-client npm test
