sudo: required
services:
  - docker
before_install:
  - docker build -t harry1989/fibonacci-client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true harry1989/fibonacci-client-test npm test
after_success:
  - docker build -t harry1989/fibonacci-api ./api
  - docker build -t harry1989/fibonacci-client ./client
  - docker build -t harry1989/fibonacci-nginx ./nginx
  - docker build -t harry1989/fibonacci-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harry1989/fibonacci-api
  - docker push harry1989/fibonacci-client
  - docker push harry1989/fibonacci-nginx
  - docker push harry1989/fibonacci-worker
deploy:
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fibonacci-docker-app"
  env: "FibonacciDockerApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-874380526196"
  bucket_path: "fibonacci-docker-app"
  on:
    branch: master
